### PR TITLE
Support for Node 4+

### PR DESCRIPTION
**Pull request by mattbasta**
- Update all of the deps
- Bump version to 2.0.0, since this is massively backwards-incompatible
- Remove unused `sys` reference, deprecated in new Node
- Travis file updated to add node 4/5

cc @tarrencev 

Fixes https://github.com/box/shalam/issues/1

### CODE REVIEW

**Comment by boxcla** [comment]
Hi @mattbasta, thanks for the pull request. Before we can merge it, we need you to sign our Contributor License Agreement. You can do so electronically here: http://opensource.box.com/cla

Once you have signed, just add a comment to this pull request saying, "CLA signed". Thanks!

**Comment by mattbasta** [comment]
CLA signed

**Comment by boxcla** [comment]
Verified that @mattbasta has just signed the CLA. Thanks, and we look forward to your contribution.

**Comment by mattbasta** [comment]
cc @mattwiller

Not sure what the timeline is for rolling out Node 4 to machines.

One other thing that's going to be a real pain in the ass is people that have upgraded to El Capitan. You'll get these cryptic messages while running `npm install`, which are caused because Xcode's command line tools aren't installed when you upgrade. You manually need to run `xcode-select --install`, which will do a whole thing. If it's a very new install, you might also not have signed the Apple EULA, and of course `node-gyp` doesn't expose that to the shell. In that case, the easiest way that I find to get that done is to just run `sudo make` in an empty directory and follow Apple's instructions.

**Comment by tarrencev** [comment]
We're already on Node 4 :+1:

And the xcode stuff isn't specific to this repo so don't think it should be a concern imo

**Comment by apfritts** [comment]
We have EOL'd Shalam and are closing down the project. Feel free to fork and carry on!

**Pull request closed without merging**
